// Generated by CoffeeScript 1.4.0
(function() {
  var compile, data, fs, jade, outputFile, print, templateFile, templateOptions;

  jade = require("jade");

  fs = require("fs");

  print = console.log;

  templateFile = "./layout.jade";

  outputFile = "./index.html";

  templateOptions = {
    pretty: true,
    filename: true
  };

  data = {
    header: require("../../temp/scripts/data/header.js"),
    canvas: require("../../temp/scripts/data/canvas.js")
  };

  compile = function() {
    return fs.readFile(templateFile, "utf8", function(err, rawTemplate) {
      var html, template;
      template = jade.compile(rawTemplate, templateOptions);
      html = template(data);
      return fs.writeFile(outputFile, html);
    });
  };

  compile();

}).call(this);
